package com.bps.plantseeds3.presentation.seeds.add_edit

data class AddEditSeedState(
    val name: String = "",
    val scientificName: String = "",
    val species: String = "",
    val variety: String = "",
    val category: String = "",
    val description: String = "",
    val plantingDepth: String = "",
    val plantingDistance: String = "",
    val plantingDates: String = "",
    val sunRequirement: String = "",
    val waterRequirement: String = "",
    val soilRequirement: String = "",
    val hardiness: String = "",
    val sowingInstructions: String = "",
    val growingInstructions: String = "",
    val harvestInstructions: String = "",
    val daysToGermination: String = "",
    val daysToHarvest: String = "",
    val harvestPeriod: String = "",
    val companionPlants: String = "",
    val avoidPlants: String = "",
    val plantSpacing: String = "",
    val rowSpacing: String = "",
    val tags: String = "",
    val notes: String = "",
    val showSuggestions: Boolean = false
) 